- name: Configure only newly created VM
  hosts: newly_created
  remote_user: ansible
  become: true
  tasks:
    - wait_for_connection:
        timeout: 300

    - include_role:
        name: "{{ item }}"
      loop:
        - common
        - monitoring
        - app
