- name: Configure only newly created VM
  hosts: newly_created
  remote_user: sysadmin
  become: true
  vars:
    ansible_ssh_private_key_file: /root/.ssh/ansible
  tasks:
    - name: Wait for SSH to become available
      wait_for_connection:
        timeout: 300

    - include_role:
        name: "{{ item }}"
      loop:
        - common
        - monitoring
        - app
